version: 2

updates:
  - package-ecosystem: docker
    directories:
      - /
      - /backend
      - /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      docker-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      compose-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
