AWSTemplateFormatVersion: "2010-09-09"

Description: FitTrack VPC interface and gateway endpoints.

Parameters:
  NetworkStackName:
    Description: Name of the deployed network stack
    Type: String

Resources:
  InterfaceEndpointsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTPS from application subnets to VPC endpoints
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      SecurityGroupIngress:
        - Description: HTTPS from application subnet AZ 1
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.20.2.0/24
        - Description: HTTPS from application subnet AZ 2
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.20.3.0/24
      Tags:
        - Key: Name
          Value: fit-track-prod-vpc-endpoints-sg-eu-central-1
        - Key: Environment
          Value: prod
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcrApiInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.api"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: fit-track-prod-vpce-ecr-api-eu-central-1
        - Key: Environment
          Value: prod
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcrDkrInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: fit-track-prod-vpce-ecr-dkr-eu-central-1
        - Key: Environment
          Value: prod
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcsInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecs"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: fit-track-prod-vpce-ecs-eu-central-1
        - Key: Environment
          Value: prod
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcsAgentInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecs-agent"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: fit-track-prod-vpce-ecs-agent-eu-central-1
        - Key: Environment
          Value: prod
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcsTelemetryInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecs-telemetry"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: fit-track-prod-vpce-ecs-telemetry-eu-central-1
        - Key: Environment
          Value: prod
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  S3GatewayEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Gateway"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowEcrImageLayers
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::prod-${AWS::Region}-starport-layer-bucket/*"
      RouteTableIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppRouteTableId"
      Tags:
        - Key: Name
          Value: fit-track-prod-vpce-s3-eu-central-1
        - Key: Environment
          Value: prod
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

Outputs:
  EcrApiInterfaceEndpointId:
    Description: ID of the Amazon ECR API interface endpoint
    Value: !Ref EcrApiInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcrApiInterfaceEndpointId"

  EcrDkrInterfaceEndpointId:
    Description: ID of the Amazon ECR Docker Registry interface endpoint
    Value: !Ref EcrDkrInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcrDkrInterfaceEndpointId"

  EcsInterfaceEndpointId:
    Description: ID of the Amazon ECS interface endpoint
    Value: !Ref EcsInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcsInterfaceEndpointId"

  EcsAgentInterfaceEndpointId:
    Description: ID of the Amazon ECS agent interface endpoint
    Value: !Ref EcsAgentInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcsAgentInterfaceEndpointId"

  EcsTelemetryInterfaceEndpointId:
    Description: ID of the Amazon ECS telemetry interface endpoint
    Value: !Ref EcsTelemetryInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcsTelemetryInterfaceEndpointId"

  S3GatewayEndpointId:
    Description: ID of the Amazon S3 gateway endpoint
    Value: !Ref S3GatewayEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-S3GatewayEndpointId"
