AWSTemplateFormatVersion: "2010-09-09"

Description: FitTrack private ECR, ECS, Systems Manager, Secrets Manager, and CloudWatch Logs VPC endpoints.

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
  NetworkStackName:
    Description: Name of the deployed network stack.
    Type: String

Resources:
  InterfaceEndpointsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for HTTPS access from ECS instances to interface endpoints.
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpc-endpoints-sg-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcrApiInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.api"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ecr-api-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcrDkrInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ecr-dkr-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcsInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecs"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ecs-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcsAgentInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecs-agent"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ecs-agent-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  EcsTelemetryInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecs-telemetry"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ecs-telemetry-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  SsmInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssm"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ssm-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  SsmMessagesInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssmmessages"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ssmmessages-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  Ec2MessagesInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2messages"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-ec2messages-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  CloudWatchLogsInterfaceEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowWriteLogEvents
            Effect: Allow
            Principal: "*"
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-logs-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  SecretsManagerInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz1Id"
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppSubnetAz2Id"
      SecurityGroupIds:
        - !Ref InterfaceEndpointsSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-secretsmanager-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

  S3GatewayEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Gateway"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowEcrImageLayers
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::prod-${AWS::Region}-starport-layer-bucket/*"
      RouteTableIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-AppRouteTableId"
      Tags:
        - Key: Name
          Value: !Sub fit-track-${Environment}-vpce-s3-eu-central-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: fit-track
        - Key: Component
          Value: endpoints

Outputs:
  EcrApiInterfaceEndpointId:
    Description: ID of the Amazon ECR API interface endpoint.
    Value: !Ref EcrApiInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcrApiInterfaceEndpointId"

  EcrDkrInterfaceEndpointId:
    Description: ID of the Amazon ECR Docker Registry interface endpoint.
    Value: !Ref EcrDkrInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcrDkrInterfaceEndpointId"

  EcsInterfaceEndpointId:
    Description: ID of the Amazon ECS interface endpoint.
    Value: !Ref EcsInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcsInterfaceEndpointId"

  EcsAgentInterfaceEndpointId:
    Description: ID of the Amazon ECS agent interface endpoint.
    Value: !Ref EcsAgentInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcsAgentInterfaceEndpointId"

  EcsTelemetryInterfaceEndpointId:
    Description: ID of the Amazon ECS telemetry interface endpoint.
    Value: !Ref EcsTelemetryInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-EcsTelemetryInterfaceEndpointId"

  SsmInterfaceEndpointId:
    Description: ID of the AWS Systems Manager interface endpoint.
    Value: !Ref SsmInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-SsmInterfaceEndpointId"

  SsmMessagesInterfaceEndpointId:
    Description: ID of the AWS Systems Manager Messages interface endpoint.
    Value: !Ref SsmMessagesInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-SsmMessagesInterfaceEndpointId"

  Ec2MessagesInterfaceEndpointId:
    Description: ID of the Amazon EC2 Messages interface endpoint.
    Value: !Ref Ec2MessagesInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-Ec2MessagesInterfaceEndpointId"

  CloudWatchLogsInterfaceEndpointId:
    Description: ID of the Amazon CloudWatch Logs interface endpoint.
    Value: !Ref CloudWatchLogsInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-CloudWatchLogsInterfaceEndpointId"

  SecretsManagerInterfaceEndpointId:
    Description: ID of the AWS Secrets Manager interface endpoint.
    Value: !Ref SecretsManagerInterfaceEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-SecretsManagerInterfaceEndpointId"

  S3GatewayEndpointId:
    Description: ID of the Amazon S3 gateway endpoint.
    Value: !Ref S3GatewayEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-S3GatewayEndpointId"

  InterfaceEndpointsSecurityGroupId:
    Description: Security group ID attached to all interface endpoints.
    Value: !GetAtt InterfaceEndpointsSecurityGroup.GroupId
    Export:
      Name: !Sub "${AWS::StackName}-InterfaceEndpointsSecurityGroupId"
